### ISSUE TITLE
Programm crasht beim starten

### ISSUE THREAD

**Issue by Regulant** [TheDonDope/kindergarten#10]
Programm ausführen -> Abrechnungen -> Neu -> Vendor anlegen -> Ok -> Programm schließen -> 
Programm ausführen -> splash screen wird kurz angezeigt -> crash

git checkout kindergarten.sqlite danach kann ich es wieder ausführen.

commit 600c779335c73fd22af4a1abe59ae265839378eb

[database nach crash.zip](https://github.com/clear-group-ausbildung/kindergarten/files/1707401/database.nach.crash.zip)

Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at de.clearit.kindergarten.appliance.vendor.VendorHomeModel.<clinit>(VendorHomeModel.java:39)
	at de.clearit.kindergarten.appliance.vendor.VendorAppliance.createHomeFrame(VendorAppliance.java:82)
	at com.jgoodies.desktop.AbstractAppliance.homeFrame(AbstractAppliance.java:93)
	at com.jgoodies.desktop.AbstractAppliance.activate(AbstractAppliance.java:82)
	at de.clearit.kindergarten.application.KindergartenApplication.createAndShowGUI(KindergartenApplication.java:97)
	at com.jgoodies.uif2.application.UIFApplication.startup(UIFApplication.java:94)
	at com.jgoodies.application.Application$1.run(Application.java:371)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at de.clearit.kindergarten.domain.VendorService.fromEntity(VendorService.java:54)
	at de.clearit.kindergarten.domain.VendorService.fromEntity(VendorService.java:13)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.clearit.kindergarten.domain.AbstractResourceService.fromEntities(AbstractResourceService.java:98)
	at de.clearit.kindergarten.domain.AbstractResourceService.<init>(AbstractResourceService.java:33)
	at de.clearit.kindergarten.domain.VendorService.<init>(VendorService.java:22)
	at de.clearit.kindergarten.domain.VendorService.<clinit>(VendorService.java:15)
	... 21 more

**Comment by CyroXs** [comment]
Fehlerbehandlung müsste dann da noch rein.
Aber ich glaube das Grundlegende Problem ist das die VendorNumbern die Persistiert werden nicht die richtige VendorID hat. (ist eine annahme).
Kannst du mal in die DB gucken und nachsehen ob die VendorNumber die erwartete VendorID hat?

**Comment by mjaeger13** [comment]
@TheDonDope hat das Thema behoben...CLOSED
