### ISSUE TITLE
Verkaufsdatenübersicht Filter

### ISSUE THREAD

**Issue by TheDonDope** [TheDonDope/kindergarten#44]
Neue Sortierungsoptionen in der Verkaufsübersicht: "Standard" (chronologisch nach Anlagadatum) oder "Nach Verkäufer und Verkäufernummer"

**Comment by TheDonDope** [comment]
Gemeint ist:
- 1 neue ComboBox links neben der vorhandenen Filter ComboBox, mit dem Label "Sortiert nach:"
- Die ComboBox hat zwei Elemente -> "Chronologisch", "Nach Verkäufer und Verkäufernummer"

Sortiermodus "Chronologisch" bedeutet:
- "keine" Sortierung, denn die Verkäufe werden bereits jetzt einfach nacheinander chronologisch nach Anlegedatum angezeigt.

Sortiermodus "Nach Verkäufer und Verkäufernummer" bedeutet:
- Zuerst wird nach Verkäufernachname, Vorname sortiert (alphabetisch aufsteigend)
- Danach (da jeder Verkäufer ja mehrere Verkäufernummern haben kann), numerisch aufsteigend nach Verkäufernummer

**Comment by kiwikidy** [comment]
Erledigt- Sortiert nun nach Verkäufername und Nummer

**Comment by Regulant** [comment]
Der feature/vendor-filter branch ist nicht in develop gemerged.
Hier steht noch das Problem, dass wenn ein neuer Vendor angelegt wird dieser doppelt angelegt und eine Nullpointer Exception geworfen wird.
Neu -> Daten eintragen -> 1. Klick auf ok -> Exception -> 2. Klick auf ok -> wechselt wieder auf VendorHomeView und der angelegte Verkäufer steht 2 mal drinn.

[AWT-EventQueue-0] DEBUG de.clearit.kindergarten.domain.AbstractResourceService - AbstractResourceService::getAll()
java.lang.NullPointerException
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.lambda$filterPurchases$3(PurchaseHomeModel.java:238)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.filterPurchases(PurchaseHomeModel.java:240)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.lambda$new$0(PurchaseHomeModel.java:80)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange0(ExtendedPropertyChangeSupport.java:282)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:224)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:179)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange0(ExtendedPropertyChangeSupport.java:296)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:261)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:201)
	at com.jgoodies.binding.beans.Model.firePropertyChange(Model.java:430)
	at com.jgoodies.binding.list.SelectionInList.fireValueChange(SelectionInList.java:862)
	at com.jgoodies.binding.list.SelectionInList$SelectionIndexChangeHandler.propertyChange(SelectionInList.java:1241)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange0(ExtendedPropertyChangeSupport.java:282)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:224)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:179)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange0(ExtendedPropertyChangeSupport.java:296)
	at com.jgoodies.binding.beans.ExtendedPropertyChangeSupport.firePropertyChange(ExtendedPropertyChangeSupport.java:261)
	at com.jgoodies.binding.beans.Model.firePropertyChange(Model.java:458)
	at com.jgoodies.binding.value.AbstractValueModel.fireValueChange(AbstractValueModel.java:129)
	at com.jgoodies.binding.value.ValueHolder.setValue(ValueHolder.java:233)
	at com.jgoodies.binding.value.ValueHolder.setValue(ValueHolder.java:181)
	at com.jgoodies.binding.list.SelectionInList.setSelectionIndex(SelectionInList.java:702)
	at com.jgoodies.binding.list.SelectionInList$ListDataChangeHandler.intervalRemoved(SelectionInList.java:1094)
	at com.jgoodies.binding.list.ArrayListModel.fireIntervalRemoved(ArrayListModel.java:438)
	at com.jgoodies.binding.list.ArrayListModel.clear(ArrayListModel.java:188)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.refreshVendorList(PurchaseHomeModel.java:328)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.onPostCreate(PurchaseHomeModel.java:192)
	at de.clearit.kindergarten.appliance.vendor.VendorHomeModel.lambda$editItem$0(VendorHomeModel.java:99)
	at de.clearit.kindergarten.appliance.vendor.VendorEditorModel.performAccept(VendorEditorModel.java:162)
	at com.jgoodies.jsdl.core.pane.form.FormPane$FormPaneAction.actionPerformed(FormPane.java:177)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Pictarin** [comment]
fixed und auf develop implementiert
