### ISSUE TITLE
Verkäufe Tab kann nicht geöffnet werden

### ISSUE THREAD

**Issue by Regulant** [TheDonDope/kindergarten#9]
Programm starten -> Klick auf Verkäufe ->

commit 600c779335c73fd22af4a1abe59ae265839378eb

Das Problem ist in PurchaseService, Zeile 104 getItemSumByPurchases Methode, der Fehler wird nach der letzten Methode .get() geworfen. Der zu übergebene Parameter listPurchases ist leer bzw. nicht vorhanden.

Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at de.clearit.kindergarten.domain.PurchaseService.getItemSumByPurchases(PurchaseService.java:105)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.refreshSummary(PurchaseHomeModel.java:166)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.<init>(PurchaseHomeModel.java:64)
	at de.clearit.kindergarten.appliance.purchase.PurchaseHomeModel.getInstance(PurchaseHomeModel.java:70)
	at de.clearit.kindergarten.appliance.purchase.PurchaseAppliance.createHomeFrame(PurchaseAppliance.java:74)
	at com.jgoodies.desktop.AbstractAppliance.homeFrame(AbstractAppliance.java:93)
	at com.jgoodies.desktop.AbstractAppliance.activate(AbstractAppliance.java:82)
	at com.jgoodies.desktop.DesktopManager$ApplianceActivationAction.actionPerformed(DesktopManager.java:664)
	at com.jgoodies.desktop.util.WrappedAction.delegateActionPerformed(WrappedAction.java:84)
	at com.jgoodies.desktop.RejectableAction.access$000(RejectableAction.java:24)
	at com.jgoodies.desktop.RejectableAction$1.run(RejectableAction.java:57)
	at com.jgoodies.desktop.DesktopManager$4.run(DesktopManager.java:434)
	at com.jgoodies.desktop.DesktopManager.allModalFramesClosing(DesktopManager.java:440)
	at com.jgoodies.desktop.RejectableAction.actionPerformed(RejectableAction.java:60)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[database.zip](https://github.com/clear-group-ausbildung/kindergarten/files/1707320/database.zip)

**Comment by mjaeger13** [comment]
@TheDonDope Hat das Thema behoben...CLOSED
